version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    depends_on:
      - user-service
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge
