server:
  port: 9008
spring:
  application:
    name: db-per-service
  datasource:
    url: jdbc:h2:mem:dbperservice;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
